### ISSUE TITLE
rename repository and update django version

### ISSUE THREAD

**Issue by dkdndes** [codefreshdemo/cf-example-python-djanga#1]
I believe you mean Django, with "o" and not "a"

Could you also provide an example with Django 2+ and possible add Channels? I am not sure how I can test WebSockets within your environment; same [here](https://codefresh.io/docs/docs/learn-by-example/python/djanga/)

**Comment by kostis-codefresh** [comment]
The repository was renamed and now uses Django 2+

You should be able to test channels with service containers. https://codefresh.io/docs/docs/codefresh-yaml/service-containers/

I will see if I can add an example, but since Codefresh is programming language agnostic you can imagine that it is difficult to cover all programming languages, all frameworks and all features in dedicated examples.
